# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0003_auto_20170918_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
    ]
