# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0007_task_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
    ]
