# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0010_auto_20171129_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approval_date',
            field=models.DateField(null=True),
        ),
    ]
