# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 09:08
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='profile-pictures'),
        ),
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=''),
        ),
    ]
