# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0011_auto_20171213_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
