# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0012_auto_20171213_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
