# Generated by Django 2.2.12 on 2020-08-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0013_delete_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='website',
            field=models.CharField(max_length=50, null=True, verbose_name='Website'),
        ),
    ]
