# Generated by Django 2.2.13 on 2021-02-17 12:53

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0014_task_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=django_markdown.models.MarkdownField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='Description (max. 5000 characters)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_de',
            field=models.CharField(max_length=5000, null=True, verbose_name='Description (max. 5000 characters)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en_us',
            field=models.CharField(max_length=5000, null=True, verbose_name='Description (max. 5000 characters)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead_text',
            field=models.CharField(max_length=600, verbose_name='Lead text (max. 600 characters)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead_text_de',
            field=models.CharField(max_length=600, null=True, verbose_name='Lead text (max. 600 characters)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead_text_en_us',
            field=models.CharField(max_length=600, null=True, verbose_name='Lead text (max. 600 characters)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title (max. 100 characters)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Title (max. 100 characters)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name='Title (max. 100 characters)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='Description (max. 5000 characters)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description_de',
            field=models.CharField(max_length=5000, null=True, verbose_name='Description (max. 5000 characters)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description_en_us',
            field=models.CharField(max_length=5000, null=True, verbose_name='Description (max. 5000 characters)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead_text',
            field=models.CharField(max_length=600, verbose_name='Lead text (max. 600 characters)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead_text_de',
            field=models.CharField(max_length=600, null=True, verbose_name='Lead text (max. 600 characters)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead_text_en_us',
            field=models.CharField(max_length=600, null=True, verbose_name='Lead text (max. 600 characters)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title (max. 100 characters)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Title (max. 100 characters)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name='Title (max. 100 characters)'),
        ),
    ]
