# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0002_auto_20160617_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='osschallenge.Project'),
        ),
    ]
