# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0005_auto_20171004_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='points',
            new_name='total_points',
        ),
        migrations.AddField(
            model_name='profile',
            name='quarter_points',
            field=models.IntegerField(default=0),
        ),
    ]
