# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0006_account_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='anti_spam',
        ),
    ]
