# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0007_remove_account_anti_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='anti_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default=b'No contact details', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.CharField(default=b'No links', max_length=50),
        ),
    ]
