# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0008_auto_20170224_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='links',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
