# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0008_task_approval_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quarter_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_points',
        ),
    ]
