# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osschallenge', '0009_auto_20170308_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contributers',
        ),
        migrations.AddField(
            model_name='task',
            name='contributors',
            field=models.ManyToManyField(related_name='task_contributors', to=settings.AUTH_USER_MODEL, verbose_name='Contributors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead_text',
            field=models.CharField(max_length=300, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='licence',
            field=models.CharField(max_length=50, verbose_name='Licence'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentors',
            field=models.ManyToManyField(related_name='project_mentors', to=settings.AUTH_USER_MODEL, verbose_name='Mentors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.CharField(max_length=50, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead_text',
            field=models.CharField(max_length=300, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
