# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0010_auto_20170317_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_de',
            field=models.CharField(max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en_us',
            field=models.CharField(max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='lead_text_de',
            field=models.CharField(max_length=300, null=True, verbose_name='Lead text'),
        ),
        migrations.AddField(
            model_name='project',
            name='lead_text_en_us',
            field=models.CharField(max_length=300, null=True, verbose_name='Lead text'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_de',
            field=models.CharField(max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_en_us',
            field=models.CharField(max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='task',
            name='lead_text_de',
            field=models.CharField(max_length=300, null=True, verbose_name='Lead text'),
        ),
        migrations.AddField(
            model_name='task',
            name='lead_text_en_us',
            field=models.CharField(max_length=300, null=True, verbose_name='Lead text'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
