# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osschallenge', '0011_auto_20170320_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contributors',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='assignee_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='osschallenge.Project'),
        ),
    ]
