# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0014_auto_20170324_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(default=True),
        ),
    ]
