# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0015_task_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
