# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0016_auto_20170324_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tasks_done',
        ),
    ]
