# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0017_remove_profile_tasks_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_checked',
            field=models.BooleanField(default=False),
        ),
    ]
