# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0019_auto_20170418_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.ImageField(default=b'osschallenge/pictures/no-img.jpg', upload_to=b'osschallenge/pictures/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
