# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0020_auto_20170418_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.ImageField(default=b'osschallenge/pictures/no-img.jpg', null=True, upload_to=b'osschallenge/pictures/'),
        ),
    ]
