# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0021_auto_20170418_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.ImageField(null=True, upload_to=b'osschallenge/pictures/'),
        ),
    ]
