# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0024_auto_20170419_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.FileField(null=True, upload_to=b'/home/jonas/gitty/work/oss-challenge.src/oss_challenge/osschallenge/pictures'),
        ),
    ]
