# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0025_auto_20170419_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.FileField(default=b'/home/jonas/gitty/work/oss-challenge.src/oss_challenge/osschallenge/pictures/file', null=True, upload_to=b'/home/jonas/gitty/work/oss-challenge.src/oss_challenge/osschallenge/pictures'),
        ),
    ]
