# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0027_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.FileField(default=b'/home/jonas/gitty/work/oss-challenge.src/oss_challenge/osschallenge/pictures/example.jpg', null=True, upload_to=b'/home/jonas/gitty/work/oss-challenge.src/oss_challenge/osschallenge/pictures'),
        ),
    ]
