# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 11:05
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0038_auto_20170504_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(default=b'/home/jonas/gitty/work/oss-challenge.src/oss_challenge/osschallenge/media/example.jpg', upload_to=b''),
        ),
    ]
