# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0039_auto_20170504_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(default=b'example.jpg', upload_to=b''),
        ),
    ]
