# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 13:24
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0040_auto_20170512_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=b''),
        ),
    ]
