# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0045_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=b'profile-pictures'),
        ),
    ]
