# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0047_profile_rank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranks',
            new_name='Rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
    ]
