# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0048_auto_20170602_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='rank',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
        migrations.AddField(
            model_name='rank',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rank',
            name='required_points',
            field=models.IntegerField(default=0),
        ),
    ]
