# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osschallenge', '0049_auto_20170612_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='order',
        ),
    ]
